apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  dependsOn:
  - name: prometheus-operator
    namespace: metrics
  interval: 1m0s
  targetNamespace: kube-system