---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vpn-http
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - vpn.notusa.uk
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /api
      backendRefs:
        - name: {{ .Release.Name }}-api
          port: 80
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: {{ .Release.Name }}
          port: 80
    - matches:
      - path:
          type: PathPrefix
          value: /signalexchange.SignalExchange
      backendRefs:
        - name: {{ .Release.Name }}-signal
          port: 80
    - matches:
      - path:
          type: PathPrefix
          value: /management.ManagementService
      backendRefs:
        - name: {{ .Release.Name }}-management
          port: 80
    - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
          statusCode: 301 
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: vpn-grpc
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - vpn.notusa.uk
  rules:
    - matches:
      - method:
          service: signalexchange.SignalExchange
      backendRefs:
      - name: {{ .Release.Name }}-signal
        port: 80
    - matches:
      - method:
          service: management.ManagementService
      backendRefs:
      - name: {{ .Release.Name }}-management
        port: 80
