apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netbird-management-config-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: netbird-client-id
      remoteRef:
        key: auth.netbird
        property: client_id
    - secretKey: netbird-token
      remoteRef:
        key: auth.netbird
        property: token
    - secretKey: turn-password
      remoteRef:
        key: turn-password
        property: turn-password
  target:
    name: netbird-management-config-secret
    template:
      engineVersion: v2
      stringData:
        management.json: |
            {
              "Stuns": [
                {
                  "Proto": "udp",
                  "URI": "stun:turn.notusa.uk:3478",
                  "Username": "",
                  "Password": null
                }
              ],
              "TURNConfig": {
                "Turns": [
                  {
                    "Proto": "udp",
                    "URI": "turn:turn.notusa.uk:3478",
                    "Username": "self",
                    "Password": "{{ `{{ .turn-password }}` }}"
                  }
                ],
                "CredentialsTTL": "12h",
                "Secret": "secret",
                "TimeBasedCredentials": false
              },
              "Signal": {
                "Proto": "https",
                "URI": "vpn.notusa.uk:443",
                "Username": "",
                "Password": null
              },
              "Datadir": "",
              "DataStoreEncryptionKey": "",
              "StoreConfig": {
                "Engine": "jsonfile"
              },
              "HttpConfig": {
                "Address": "0.0.0.0:443",
                "AuthIssuer": "https://auth.notusa.uk/application/o/netbird/",
                "AuthAudience": "{{ `{{ .netbird-client-id }}` }}",
                "AuthKeysLocation": "https://auth.notusa.uk/application/o/netbird/jwks/",
                "AuthUserIDClaim": "",
                "CertFile": "",
                "CertKey": "",
                "IdpSignKeyRefreshEnabled": false,
                "OIDCConfigEndpoint": "https://auth.notusa.uk/application/o/netbird/.well-known/openid-configuration"
              },
              "IdpManagerConfig": {
                "ManagerType": "authentik",
                "ClientConfig": {
                  "Issuer": "https://auth.notusa.uk/application/o/netbird/",
                  "TokenEndpoint": "https://auth.notusa.uk/application/o/token/",
                  "ClientID": "{{ `{{ .netbird-client-id }}` }}",
                  "ClientSecret": "",
                  "GrantType": "client_credentials"
                },
                "ExtraConfig": {
                  "Password": "{{ `{{ .netbird-token }}` }}",
                  "Username": "Netbird"
                },
                "Auth0ClientCredentials": null,
                "AzureClientCredentials": null,
                "KeycloakClientCredentials": null,
                "ZitadelClientCredentials": null
              },
              "DeviceAuthorizationFlow": {
                "Provider": "hosted",
                "ProviderConfig": {
                  "Audience": "{{ `{{ .netbird-client-id }}` }}",
                  "AuthorizationEndpoint": "",
                  "Domain": "",
                  "ClientID": "{{ `{{ .netbird-client-id }}` }}",
                  "ClientSecret": "",
                  "TokenEndpoint": "https://auth.notusa.uk/application/o/token/",
                  "DeviceAuthEndpoint": "https://auth.notusa.uk/application/o/device/",
                  "Scope": "openid",
                  "UseIDToken": false,
                  "RedirectURLs": null
                }
              },
              "PKCEAuthorizationFlow": {
                "ProviderConfig": {
                  "Audience": "{{ `{{ .netbird-client-id }}` }}",
                  "ClientID": "{{ `{{ .netbird-client-id }}` }}",
                  "ClientSecret": "",
                  "Domain": "",
                  "AuthorizationEndpoint": "https://auth.notusa.uk/application/o/authorize/",
                  "TokenEndpoint": "https://auth.notusa.uk/application/o/token/",
                  "Scope": "openid profile email offline_access api",
                  "RedirectURLs": [
                    "http://localhost:53000"
                  ],
                  "UseIDToken": false
                }
              }
            }
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netbird-generated-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: client-id
      remoteRef:
        key: auth.netbird
        property: client_id
  target:
    name: netbird-generated-secret