        # homepage:
        #   enabled: true
        #   name: "Traefik"
        #   href: https://traefik.notusa.uk/dashboard/
        #   group: "system"
        #   widget:
        #     type: traefik
        #     url: http://traefik-traefik.traefik.svc.cluster.local:9000
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium
  namespace: kube-system
spec:
  controllerName: io.cilium/gateway-controller
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notusa-uk-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - '*.notusa.uk'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: notusa-uk-cert
  usages:
    - digital signature
    - key encipherment
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: cilium-gateway
  namespace: kube-system
spec:
  gatewayClassName: cilium
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.notusa.uk'
      name: web
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.notusa.uk'
      name: websecure
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ''
            kind: Secret
            name: notusa-uk-cert
        mode: Terminate
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-tcp-gateway
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: traefik
  listeners:
  - name: ldap
    port: 389
    protocol: TCP
  - name: ldaps
    port: 636
    protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traefik-dashboard
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: {{ .Release.Namespace }}
  hostnames:
    - traefik.notusa.uk
  rules:
    - backendRefs:
        - name: api@internal
          group: traefik.io
          kind: TraefikService
      filters:
      - type: ExtensionRef
        extensionRef:
          group: traefik.io
          kind: Middleware
          name: authentik
    - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
          statusCode: 301 
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: traefik-http-redirect
#   namespace: {{ .Release.Namespace }}
# spec:
#   parentRefs:
#     - name: traefik-gateway
#       namespace: {{ .Release.Namespace }}
#       sectionName: web
#   hostnames:
#     - traefik.notusa.uk
#   rules:
#   - filters:
#     - type: RequestRedirect
#       requestRedirect:
#         scheme: https
#         statusCode: 301