        # homepage:
        #   enabled: true
        #   name: "Traefik"
        #   href: https://traefik.notusa.uk/dashboard/
        #   group: "system"
        #   widget:
        #     type: traefik
        #     url: http://traefik-traefik.traefik.svc.cluster.local:9000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notusa-uk-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - '*.notusa.uk'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: notusa-uk-cert
  usages:
    - digital signature
    - key encipherment
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-tcp-gateway
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: traefik
  listeners:
  - name: ldap
    port: 389
    protocol: TCP
  - name: ldaps
    port: 636
    protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traefik-dashboard
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: {{ .Release.Namespace }}
  hostnames:
    - traefik.notusa.uk
  rules:
    - backendRefs:
        - name: api@internal
          group: traefik.io
          kind: TraefikService
    - filters:
      - type: ExtensionRef
        extensionRef:
          group: traefik.io
          kind: Middleware
          name: authentik
      - type: RequestRedirect
        requestRedirect:
          scheme: https
          statusCode: 301