apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authentik
  namespace: {{ .Release.Namespace }}
spec:
  forwardAuth:
    address: https://authentik-authentik-proxy.authentik.svc.cluster.local:10228/outpost.goauthentik.io/auth/traefik 
    trustForwardHeader: true
    tls:
      insecureSkipVerify: true
    authResponseHeaders:
    - authorization
    - X-authentik-username
    - X-authentik-groups
    - X-authentik-email
    - X-authentik-name
    - X-authentik-uid
    - X-authentik-jwt
    - X-authentik-meta-jwks
    - X-authentik-meta-outpost
    - X-authentik-meta-provider
    - X-authentik-meta-app
    - X-authentik-meta-version
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: websocket-fix
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"

      