apiVersion: batch/v1
kind: Job
metadata:
  name: gitea-config-{{ include (print $.Template.BasePath "/config-source.yaml") . | sha256sum | trunc 7 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  backoffLimit: 10
  template:
    spec:
      serviceAccountName: argocd-update
      restartPolicy: Never
      initContainers:
        - name: apply
          image: golang:1.19-alpine
          env:
            - name: GITEA_HOST
              value: http://gitea-http:3000
            - name: GITEA_USER
              valueFrom:
                secretKeyRef:
                  name: gitea-admin-secret
                  key: username
            - name: GITEA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-admin-secret
                  key: password
          workingDir: /go/src/gitea-config
          command:
            - sh
            - -c
          args:
            - |
              go get .
              go run .
          volumeMounts:
            - name: source
              mountPath: /go/src/gitea-config
      containers:
      # - name: update-resource-container-a
      #   image: bitnami/kubectl
      #   command: ['sh', '-c', "kubectl get application argocd -n argocd -o json | jq '.spec.source.repoURL |= sub(\"https://github.com/Cal3165/homelab\"; \"http://gitea-http.gitea:3000/ops/homelab\")' | kubectl apply -f -"]
      - name: update-resource-container-appofapps
        image: bitnami/kubectl
        command: ['sh', '-c', "kubectl get application app-of-apps -n argocd -o json | jq '.spec.source.repoURL |= sub(\"https://github.com/Cal3165/homelab\"; \"http://gitea-http.gitea:3000/ops/homelab\")' | kubectl apply -f -"]
      volumes:
        - name: source
          configMap:
            name: gitea-config-source

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: update-argo-apps
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
rules:
  - verbs:
      - get
      - list
      - update
      - watch
      - patch
    apiGroups:
      - argoproj.io
    resources:
      - applications
      - applicationsets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-update
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-update-apps
  namespace: argocd
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
subjects:
  - kind: ServiceAccount
    name: argocd-update
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: update-argo-apps
  apiGroup: rbac.authorization.k8s.io