apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.11
  share: /mnt/HDD/Apps
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nolock