elementweb:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.notusa.uk"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - host: &frontend_host chat.notusa.uk
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: element-tls-certificate
        hosts:
          - *frontend_host
  config:
    default:
      base_url: https://matrix.notusa.uk
      server_name: notusa.uk

dendrite:
  dendrite_config:
    global:
      server_name: matrix.notusa.uk
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostName: matrix.notusa.uk
    tls:
      - hosts:
          - matrix.notusa.uk
        secretName: matrix-tls-certificate
  postgresql:
    enabled: true
    primary:
      persistence:
        storageClass: longhorn
