traefik:
  globalArguments:
  - "--global.checknewversion"
  - "--providers.kubernetesgateway.experimentalchannel=true"
  experimental:
    kubernetesGateway:
      enabled: true
      namespacePolicy: All
      certificate:
        name: notusa-uk-cert
  ports:
    web:
      port: 80
    websecure:
      port: 443
    ldap:
      port: 389
      exposedPort: 389
      protocol: TCP
      expose:
        default: true
      forwardedHeaders:
        enabled: false
      tls:
        enabled: false
    ldaps:
      enabled: true
      port: 636
      exposedPort: 636
      protocol: TCP
      expose:
        default: true
      forwardedHeaders:
        enabled: false
      tls:
        enabled: false
  ingressRoute:
    dashboard:
      enabled: false
      # annotations: {}
      # matchRule: Host(`traefik.notusa.uk`)
      # entryPoints: ["web"]
      # middlewares: ["authentik"]
      # tls: {}
  podSecurityContext:
    sysctls:
    - name: "net.ipv4.ip_unprivileged_port_start"
      value: "0"

