metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.0.0.110, mac: 'C6:81:D2:BB:4E:95', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 10.0.0.111, mac: '42:34:36:66:0F:BA', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 10.0.0.112, mac: 'C6:6A:6F:F7:26:DD', disk: sda, network_interface: eno1}
    workers:
      hosts:
        metal3: {ansible_host: 10.0.0.113, mac: '32:BF:91:25:99:D3', disk: sda, network_interface: eno1}
