metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.0.0.110, mac: 'c6:81:d2:bb:4e:95', disk: sda, network_interface: ens19}
        metal1: {ansible_host: 10.0.0.111, mac: '42:34:36:66:0f:ba', disk: sda, network_interface: ens19}
        metal2: {ansible_host: 10.0.0.112, mac: 'c6:6a:6f:f7:26:dd', disk: sda, network_interface: ens19}
    workers:
      hosts:
        metal3: {ansible_host: 10.0.0.113, mac: '32:bf:91:25:99:d3', disk: sda, network_interface: ens19}
