---
apiVersion: app.terraform.io/v1alpha2
kind: AgentPool
metadata:
  name: agent-pool
spec:
  organization: cal-homelab
  token:
    secretKeyRef:
      name: terraformrc
      key: organization_token
  name: agent-pool
  agentTokens:
    - name: agent-token
  agentDeployment:
    replicas: 1
    spec:
      containers:
        - name: tfc-agent
          image: "hashicorp/tfc-agent:1.13.1"
  # Enable autoscaling
    autoscaling:
      minReplicas: 0
      maxReplicas: 1
      cooldownPeriodSeconds: 30
      targetWorkspaces:
      - name: kube-runner