apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: authentik-setup
spec:
  organization: cal-homelab
  token:
    secretKeyRef:
      name: terraformrc
      key: organization_token
  module:
    source: "git::http://gitea-http.gitea:3000/ops/homelab.git//authentik-terraform"
  outputs:
    - name: grafana_secret
      sensitive: true
    - name: argocd_secret
      sensitive: true
    - name: homepage-token
      sensitive: true
  variables:
    - name: grafana_redirect_uri
    - name: argocd_redirect_uri
    - name: authentik_url
    - name: grafana_client_id
    - name: argocd_client_id
    - name: authentik_token
  workspace:
    name: kube-runner