apiVersion: app.terraform.io/v1alpha2
kind: Project
metadata:
  name: kube-runner-project
spec:
  organization: cal-homelab
  token:
    secretKeyRef:
      name: terraformrc
      key: organization_token
  name: kube-runner-project