apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: terraform-config-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: terraform-config-secrets
  data:
    - secretKey: grafana-client-id
      remoteRef:
        key: auth.grafana
        property: client_id
    - secretKey: argocd-client-id
      remoteRef:
        key: auth.argocd
        property: client_id
    - secretKey: authentik-token
      remoteRef:
        key: authentik.secrets
        property: authentik_token