cloudflared:
  credentials:
    existingSecret: cloudflared-credentials
  config:
    tunnel: homelab
    ingress:
      - hostname: '*.notusa.uk'
        service: https://treafik-traefik.treafik
        originRequest:
          noTLSVerify: true
      - service: http_status:404

  podMonitor:
    enabled: true
    metricsEndpoints:
      - port: http
