csi-driver-nfs:
  controller:
    runOnControlPlane: true
    replicas: 2
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
                matchLabels:
                  app: csi-nfs-controller
  storageClass:
    create: false