grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - &host grafana.notusa.uk
    tls:
      - secretName: grafana-general-tls
        hosts:
          - *host
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: monitoring-system
    datasources:
      enabled: true
      searchNamespace: monitoring-system
  envFromSecret: grafana-secrets
  grafana.ini:
    server:
      root_url: https://grafana.notusa.uk
    panels:
      disable_sanitize_html: true
    auth.generic_oauth:
      enabled: true
      allow_sign_up: true
      name: Dex
      client_id: grafana-sso
      client_secret: $__env{GRAFANA_SSO_CLIENT_SECRET}
      scopes: openid profile email groups
      auth_url: https://dex.notusa.uk/auth
      token_url: https://dex.notusa.uk/token
      api_url: https://dex.notusa.uk/userinfo
