apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-terraform-configmap
data:
{{- range $path, $_ :=  .Files.Glob  "authentik-terraform/*.tf" }}    
  {{ $path | trimPrefix "authentik-terraform/" }}: |- 
{{ $.Files.Get $path | indent 4 }}
{{ end }}
{{- range $path, $_ :=  .Files.Glob  "authentik-terraform/modules/odic_app/*.tf" }}    
  {{ $path | trimPrefix "authentik-terraform/modules/odic_app/" | trim | cat "odic_app_" }}: |- 
{{ $.Files.Get $path | indent 4 }}
{{ end }}