apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authentik-terraform-secrets
  namespace: authentik
subjects:
  - kind: ServiceAccount
    name: authentik-terraform
roleRef:
  kind: Role
  name: secret-manipulation
  apiGroup: rbac.authorization.k8s.io