apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manipulation
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - leases
    verbs:
      - get
      - list
      - create
      - update
      - patch