apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authentik-terraform-secrets
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: authentik-terraform
roleRef:
  kind: Role
  name: secret-manipulation
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authentik-terraform-secrets
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: authentik-terraform
roleRef:
  kind: Role
  name: leases-manipulation
  apiGroup: coordination.k8s.io