apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-generated-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: authentik-generated-secrets
  data:
    - secretKey: authentik-secret-key
      remoteRef:
        key: authentik.secrets
        property: secret_key
    - secretKey: postgresql_password
      remoteRef:
        key: authentik.secrets
        property: postgresql_password

