apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: authentik-secret-key
  data:
    - secretKey: authentik-secret-key
      remoteRef:
        key: authentik.key
        property: secret_key
