# TODO create user and access token
# users:
#   - name: renovate
#     fullName: Renovate
#     email: bot@renovateapp.com
#     tokenSecretRef: renovate-secret # ???
organizations:
  - name: ops
    description: Operations
    teams:
      - name: Owners
        members:
          - renovate
repositories:
  - name: homelab
    owner: ops
    private: false
    migrate:
      source: https://github.com/Cal3165/homelab
      mirror: false
  - name: blog
    owner: khuedoan
    migrate:
      source: https://github.com/khuedoan/blog
      mirror: true
  - name: backstage
    owner: khuedoan
    migrate:
      source: https://github.com/khuedoan/backstage
      mirror: true
files:
  - path: appOfApps/0-base.yaml
    owner: ops
    repo: homelab
    branch: master
  - path: appOfApps/1-authentik.yaml
    owner: ops
    repo: homelab
    branch: master
  - path: appOfApps/2-gitea.yaml
    owner: ops
    repo: homelab
    branch: master