apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-terraform-configmap
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
data:
{{- range $path, $_ :=  .Files.Glob  "authentik-terraform/*.tf" }}    
  {{ $path | trimPrefix "authentik-terraform/" }}: |- 
{{ $.Files.Get $path | indent 4 }}
{{ end }}
{{- range $path, $_ :=  .Files.Glob  "authentik-terraform/modules/odic_app/*.tf" }}    
  {{ $path | trimPrefix "authentik-terraform/modules/odic_app/" | cat "odic_app_" | nospace  }}: |- 
{{ $.Files.Get $path | indent 4 }}
{{ end }}