apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-generated-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: authentik-generated-secrets
  data:
    - secretKey: authentik-secret-key
      remoteRef:
        key: authentik.secrets
        property: secret_key
    - secretKey: postgresql-password
      remoteRef:
        key: authentik.secrets
        property: postgresql_password
    - secretKey: postgresql-admin-password
      remoteRef:
        key: authentik.secrets
        property: postgresql_admin_password
    - secretKey: authentik-token
      remoteRef:
        key: authentik.secrets
        property: authentik_token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: terraform-config-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: terraform-config-secrets
  data:
    - secretKey: grafana-client-id
      remoteRef:
        key: auth.grafana
        property: client_id
    - secretKey: argocd-client-id
      remoteRef:
        key: auth.argocd
        property: client_id
    - secretKey: gitea-client-id
      remoteRef:
        key: auth.gitea
        property: client_id
    - secretKey: netbird-client-id
      remoteRef:
        key: auth.netbird
        property: client_id
    - secretKey: authentik-token
      remoteRef:
        key: authentik.secrets
        property: authentik_token
