---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-authentik-secret
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: secret
      remoteRef:
        key: authentik-setup-output
        property: argocd_secret