csi-driver-nfs:
  externalSnapshotter:
    enabled: true
  controller:
    runOnControlPlane: true
    replicas: 2
  customLabels:
  storageClass:
    create: true
    name: nfs-csi
    parameters:
      server: 10.0.0.11
      share: /mnt/HDD/Apps
    reclaimPolicy: Delete
    volumeBindingMode: Immediate