---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-authentik-secret
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: client_id
      remoteRef:
        key: auth.argocd
        property: client_id
    - secretKey: secret
      remoteRef:
        key: authentik-setup-output
        property: argocd_secret


