apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.gitea.gitea.admin.existingSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      engineVersion: v2
      data:
        username: gitea_admin
        password: {{` "{{ .password }}" `}}
  data:
    - secretKey: password
      remoteRef:
        key: gitea.admin
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-authentik-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: key
      remoteRef:
        key: auth.gitea
        property: client_id
    - secretKey: secret
      remoteRef:
        key: authentik-setup-output
        property: gitea_secret