# Gitea
- name: gitea.admin
  data:
    - key: password
      length: 32
      special: true

# Dex
- name: dex.grafana
  data:
    - key: client_secret
      length: 32
      special: false

- name: dex.gitea
  data:
    - key: client_secret
      length: 32
      special: false

# Registry
- name: registry.admin
  data:
    - key: password
      length: 32
      special: true

# Woodpecker
- name: woodpecker.agent
  data:
    - key: secret
      length: 32
      special: false

# Paperless
- name: paperless.admin
  data:
    - key: PAPERLESS_ADMIN_PASSWORD
      length: 32
      special: true

# Authentik
- name: authentik.secrets
  data:
    - key: secret_key
      length: 64
      special: false
    - key: postgresql_password
      length: 32
      special: false
    - key: postgresql_admin_password
      length: 32
      special: false
    - key: authentik_token
      length: 40
      special: false

- name: auth.grafana
  data:
    - key: client_id
      length: 32
      special: false

- name: auth.gitea
  data:
    - key: client_id
      length: 32
      special: false